name: hi_bees
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.9.13+83

environment:
  sdk: '>=2.18.5 <3.0.0'
  flutter: ">=2.8.1"
  
# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  path_provider: ^2.0.9
  sqflite: ^2.2.2
  intl: ^0.19.0
  provider: ^6.0.5
  flutter_beep: ^1.0.0
  wakelock_plus: ^1.2.10
  http: ^1.2.2
  device_info_plus: ^11.2.0
  connectivity_plus: ^6.1.1
  # in_app_purchase: ^3.1.5
  shared_preferences: ^2.1.0
  flutter_slidable: ^3.1.1
  url_launcher: ^6.1.10
  fl_chart: ^0.70.1
  picovoice_flutter: ^3.0.3
  nfc_manager: ^3.5.0
  pdf: ^3.10.8
  printing: ^5.12.0
  share_plus: ^10.1.4
  image_picker: ^1.0.7
  flutter_map: ^6.2.1
  latlong2: ^0.9.1
  flutter_local_notifications: ^17.2.4
  timezone: ^0.9.4
  flutter_timezone: ^3.0.1
  table_calendar: ^3.1.3

dev_dependencies:
  flutter_launcher_icons: ^0.14.1
  flutter_test:
    sdk: flutter




flutter_icons:
  image_path: "assets/image/hi_bees_1024.png"
  android: true
  ios: true
  adaptive_icon_backgroud: "#ffffff"
  adaptive_icon_foregroud: "assets/hi_bees_1024.png"
  
  
  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  assets:
    - assets/contexts/android/apiary_android_en_US.rhn
    - assets/contexts/android/apiary_android_pl_PL.rhn
    - assets/contexts/ios/apiary_ios_pl_PL.rhn
    - assets/contexts/ios/apiary_ios_en_US.rhn
    - assets/keyword_files/android/Hi-Maya_android_en_US.ppn
    - assets/keyword_files/android/Hi-Maya_android_pl_PL.ppn
    - assets/keyword_files/ios/Hi-Maya_ios_pl_PL.ppn
    - assets/keyword_files/ios/Hi-Maya_ios_en_US.ppn
    - assets/porcupine/porcupine_params_pl_PL.pv
    - assets/porcupine/porcupine_params_en_US.pv
    - assets/rhino/rhino_params_pl_PL.pv
    - assets/rhino/rhino_params_en_US.pv
    - assets/image/matka1.png
    - assets/image/matka11.png
    - assets/image/matka12.png
    - assets/image/hi_bees_1024.png
    - assets/image/apivarol1.png
    - assets/image/invert.png
    - assets/image/korpus.png
    - assets/image/hi_bees.png
    - assets/image/pszczola1.png
    - assets/image/zbiory.png
    - assets/image/wind.png
    - assets/image/rain.png
    - assets/image/EN.png
    - assets/image/PL.png
   # - assets/audio/sound7.mp3
  
  
  uses-material-design: true
  generate: true

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
 


  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
